
gitlab_issues:
    path:  /issues
    defaults:
        - _controller: CiscoSystemsGitlabBundle:Issue:index

gitlab_issue_delete:
    path:  /issue/{id}/delete
    defaults:
        - _controller: CiscoSystemsGitlabBundle:Issue:delete

gitlab_issue:
    path:  /issue/{id}
    defaults:
        - _controller: CiscoSystemsGitlabBundle:Issue:view

gitlab_access:
    path:  /access
    defaults:
        - _controller: CiscoSystemsGitlabBundle:Access:index

gitlab_access_delete:
    path:  /access/{id}/delete
    defaults:
        - _controller: CiscoSystemsGitlabBundle:Access:delete
    requirements:
        id: \d+
