
wg_gitlab_issues:
    pattern:  /issues
    defaults: { _controller: WGGitlabBundle:Issue:index }

wg_gitlab_access:
    pattern:  /access
    defaults: { _controller: WGGitlabBundle:Access:index }

wg_gitlab_access_delete:
    pattern:  /access/{id}/delete
    defaults: { _controller: WGGitlabBundle:Access:delete }
    requirements:
        id: \d+
