parameters:
    wg_gitlab.client.class:         WG\GitlabBundle\Client\BuzzClient
    wg_gitlab.access_manager.class: WG\GitlabBundle\Gitlab\AccessManager
    wg_gitlab.api.class:            WG\GitlabBundle\Gitlab\API

services:
    gitlab.client:
        class: %wg_gitlab.client.class%
    gitlab.access:
        class: %wg_gitlab.access_manager.class%
        arguments:
            - '@security.client'
            - '@security.context'
            - '@doctrine.orm.entity_manager'
    gitlab.api:
        class: %wg_gitlab.api.class%
        arguments:
            - '@security.client'
            - '@gitlab.access'