parameters:
    gitlab.client.class:       CiscoSystems\GitlabBundle\Client\Buzz\BuzzClient
    gitlab.api_manager.class:  CiscoSystems\GitlabBundle\API\ApiManager

services:
    # HTTP client used internally
    gitlab.client:
        class: '%gitlab.client.class%'
    # API access
    gitlab:
        class: '%gitlab.api_manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@gitlab.client'