parameters:
    wg_gitlab.client.class:       WG\GitlabBundle\Client\Buzz\BuzzClient
    wg_gitlab.api_manager.class:  WG\GitlabBundle\API\ApiManager

services:
    # HTTP client
    gitlab.client:
        class: %wg_gitlab.client.class%
    # API management
    gitlab:
        class: %wg_gitlab.api_manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.context'
            - '@gitlab.client'